server:
    contextPath: /api
    port: 8080
logging.level:
   root: ERROR
   fr.sedoo: DEBUG
   
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
                
---

spring.profiles: mysql

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mabase
        username: user
        password: user
    jpa:
       properties:
          hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

---

spring.profiles: derby

spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.DerbyDialect


                
